### PR TITLE
TCP output SSL support

### PR DESCRIPTION
**Pull request by michaelweiser**
This fixes and improves a few things in and adds SSL support to the TCP output.

### CODE REVIEW

**Comment by jamessemai** [comment]
:+1: - would very much like to see this merged, I need this as well.

**Comment by jsvd** [comment]
Would you mind doing step 2 of the contributing guide? https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by michaelweiser** [comment]
@jsvd: Sorry, done now.

**Comment by jsvd** [comment]
@michaelweiser sorry but it seems you signed the cla with a different email then [the one you used in the commits](https://github.com/logstash-plugins/logstash-output-tcp/pull/3.patch).

Could you sign the CLA with the "right" email so we can merge this? Thanks.

**Comment by michaelweiser** [comment]
Darn! :) Done it again. Sorry again.

**Comment by jamessemai** [comment]
@michaelweiser - there still seems to a problem with the CLA. Any change you might be able to resolve this?

**Comment by michaelweiser** [comment]
I've changed the author in the commits to match the CLA.

**Comment by jamessemai** [comment]
Is there someone with commit access that could tell Jenkins to go ahead and test this? :)

**Comment by jsvd** [comment]
jenkins, test it

**Comment by joemiller** [comment]
:+1: Just started using this and it seems to work fine. Can I help move this PR along somehow?

**Comment by suyograo** [comment]
LGTM

**Pull request closed without merging**
